language: ruby
notifications:
  email:
    on_success: change
    on_failure: always

before_install:
  - gem update --system $RUBYGEMS_VERSION
  - gem --version
  - gem install bundler
  - bundle --version

bundler_args: "--binstubs"

script: bin/rspec

rvm: 
  - 1.9.3

