#!/bin/sh
# /etc/init.d/teamcity -  startup script for teamcity
export TEAMCITY_DATA_PATH="/var/TeamCity/.BuildServer"
. /etc/profile.d/java.sh

case $1 in
start)
  start-stop-daemon --start  -c www-data --exec /var/TeamCity/bin/runAll.sh start
;;

stop)
  start-stop-daemon --start -c www-data  --exec  /var/TeamCity/bin/runAll.sh stop
;;

esac

exit 0
